#!/usr/bin/env bash

wget -O - https://raw.githubusercontent.com/xhente/omv-regen/master/omv-regen.sh | bash

mkdir /ORBackup

/usr/sbin/omv-regen backup && /usr/bin/rsync -axHAXWESP --progress --preallocate --remove-source-files /ORBackup /srv/mergerfs/hddpool/ONEDRIVE/ONEDRIVE_KIMIKO_OMV_BKP/ && rm -rv /ORBackup/

echo -e "\nPRONTO!\n"

exit
